server:
  port: 8083

spring:
  application:
    name: userjob-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/userjobdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.tribytegenius.CareerCompass.UserJobService: DEBUG
    org.springframework.amqp: DEBUG
