server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,http://localhost:30000}
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        - id: job-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/jobs/**
          filters:
            - Jwt
            - StripPrefix=0

        - id: userjob-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/favorites/**
          filters:
            - Jwt
            - StripPrefix=0

        - id: python-engine
          uri: http://localhost:8000
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/search/(?<segment>.*), /${segment}

jwt:
  secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.tribytegenius.gateway: DEBUG
    com.tribytegenius.CareerCompass.ApiGateway: DEBUG