server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service:8081}
          predicates:
            - Path=/api/auth/**

        - id: job-service
          uri: ${JOB_SERVICE_URL:http://job-service:8082}
          predicates:
            - Path=/api/jobs/**
          filters:
            - Jwt

        - id: userjob-service
          uri: ${USERJOB_SERVICE_URL:http://userjob-service:8083}
          predicates:
            - Path=/api/favorites/**
          filters:
            - Jwt

        - id: python-engine
          uri: ${PYTHON_SERVICE_URL:http://python-engine:8000}
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/search/(?<segment>.*), /${segment}

jwt:
  secret: ${JWT_SECRET:daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.tribytegenius.CareerCompass.ApiGateway: INFO
    root: INFO