apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: careercompass
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: andyg2025/user-service:v1
          ports:
            - containerPort: 8081
          env:
            - name: USER_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_DATABASE_URL
            - name: USER_DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_DATABASE_USERNAME
            - name: USER_DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_DATABASE_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_VHOST
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_EXPIRATION
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: careercompass
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP