apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: careercompass-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ${DOCKERHUB_USERNAME}/user-service:${IMAGE_TAG}
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

---
# User Service
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: careercompass-prod
spec:
  selector:
    app: user-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP