server:
  port: 8082

spring:
  application:
    name: job-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/jobdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

python:
  service:
    url: ${PYTHON_SERVICE_URL:http://python-engine:8000}

logging:
  level:
    com.tribytegenius.CareerCompass.JobService: INFO
    org.springframework.amqp: WARN
    root: INFO